const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Plugins.TextBox,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.TextBox.Cnds.OnClicked,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.Button.Acts.SetEnabled
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{StartBtn: 0},
	{Starttxt: 0},
	{fof: 0},
	{emotion: 0},
	{emotion2: 0},
	{emotion3: 0},
	{emotion4: 0},
	{emotion5: 0},
	{emotion6: 0},
	{ball: 0},
	{ball2: 0},
	{ball3: 0},
	{ball4: 0},
	{ball5: 0},
	{Sine: 0},
	{dots: 0},
	{Mouse: 0},
	{Audio: 0},
	{ques: 0},
	{quest: 0},
	{option: 0},
	{btn: 0},
	{btn2: 0},
	{Option: 0},
	{btn3: 0},
	{ans: 0},
	{ans3: 0},
	{ans2: 0},
	{timer: 0},
	{backward: 0},
	{forward: 0},
	{ticktok: 0},
	{btn4: 0},
	{ans4: 0},
	{FinishBtn: 0},
	{access: 0},
	{AccessCode: 0},
	{Button: 0},
	{Text: 0},
	{Sine2: 0},
	{emotions: 0},
	{balls1: 0},
	{balls2: 0},
	{opacity: 0},
	{widthTimer: 0},
	{optionSelected: 0},
	{timer2: 0},
	{widthTimer2: 0},
	{optionSelected2: 0},
	{timer3: 0},
	{widthTimer3: 0},
	{optionSelected3: 0},
	{timer4: 0},
	{widthTimer4: 0},
	{optionSelected4: 0},
	{timer5: 0},
	{widthTimer5: 0},
	{optionSelected5: 0}
];

self.InstanceType = {
	background: class extends self.ITiledBackgroundInstance {},
	StartBtn: class extends self.ISpriteInstance {},
	Starttxt: class extends self.ITextInstance {},
	fof: class extends self.ITextInstance {},
	emotion: class extends self.ISpriteInstance {},
	emotion2: class extends self.ISpriteInstance {},
	emotion3: class extends self.ISpriteInstance {},
	emotion4: class extends self.ISpriteInstance {},
	emotion5: class extends self.ISpriteInstance {},
	emotion6: class extends self.ISpriteInstance {},
	ball: class extends self.ISpriteInstance {},
	ball2: class extends self.ISpriteInstance {},
	ball3: class extends self.ISpriteInstance {},
	ball4: class extends self.ISpriteInstance {},
	ball5: class extends self.ISpriteInstance {},
	dots: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	ques: class extends self.ITextInstance {},
	quest: class extends self.ITextInstance {},
	btn: class extends self.ISpriteInstance {},
	btn2: class extends self.ISpriteInstance {},
	btn3: class extends self.ISpriteInstance {},
	ans: class extends self.ITextInstance {},
	ans3: class extends self.ITextInstance {},
	ans2: class extends self.ITextInstance {},
	timer: class extends self.ISpriteInstance {},
	backward: class extends self.ISpriteInstance {},
	forward: class extends self.ISpriteInstance {},
	ticktok: class extends self.ITextInstance {},
	btn4: class extends self.ISpriteInstance {},
	ans4: class extends self.ITextInstance {},
	FinishBtn: class extends self.IButtonInstance {},
	access: class extends self.ITiledBackgroundInstance {},
	AccessCode: class extends self.ITextInputInstance {},
	Button: class extends self.IButtonInstance {},
	Text: class extends self.ITextInstance {},
	emotions: class extends self.ISpriteInstance {},
	balls1: class extends self.ISpriteInstance {},
	balls2: class extends self.ISpriteInstance {}
}